# Generated by Django 2.2.17 on 2021-03-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kydolex_app', '0002_kydolex_list_3d_kydolex_list_blog_kydolex_list_graphic_kydolex_list_icon_kydolex_list_image_kydolex_'),
    ]

    operations = [
        migrations.AddField(
            model_name='kydolex_list_webdesign',
            name='content',
            field=models.TextField(max_length=200, null=True, verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='kydolex_list_webdesign',
            name='content_url',
            field=models.TextField(max_length=200, null=True, verbose_name='URL'),
        ),
    ]
